# Generated by Django 5.1.2 on 2024-10-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=60, null=True, unique=True)),
                ('password', models.CharField(max_length=170, null=True)),
                ('role', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
