# Generated by Django 5.1.2 on 2024-10-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='CreateUsers',
        ),
    ]
