# Generated by Django 5.1.2 on 2024-11-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
